# Generated by Django 4.2.2 on 2023-08-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_pet_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
