# Generated by Django 4.2.2 on 2023-08-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
